---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  ports:
    - port: 5000
  selector:
    app: flask-app
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
      tier: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
        tier: frontend
    spec:
      containers:
        - name: flask-app
          image: itsecat/flask-app
          ports:
            - containerPort: 5000
              name: flask-app
