---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: default
  labels:
    app: flaskapp
spec:
  ports:
    - port: 5000
  selector:
    app: flaskapp
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: default
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
      tier: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
        tier: frontend
    spec:
      containers:
        - name: flaskapp
          image: itsecat/flask-app
          ports:
            - containerPort: 5000
              name: flaskapp
